version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: survey-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: survey-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey-db
      - JWT_SECRET=supersecret

  frontend:
    build: ./frontend
    container_name: survey-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: