services:
  mongo:
    image: mongo:7
    container_name: survey-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - survey-network

  backend:
    build:
      context: ./backend
    container_name: survey-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/survey-db
      JWT_SECRET: supersecret
      NODE_ENV: development
      PORT: 5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - survey-network

  frontend:
    build:
      context: ./frontend
    container_name: survey-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - survey-network

volumes:
  mongo_data:

networks:
  survey-network:
    driver: bridge